config/routes.rb
Rails.application.routes.draw do

  root 'specifications#index'

  resources :specifications do
    get 'validate', on: :member
    get 'swagger', on: :member
    get 'api_explorer', on: :member
    get 'api_reference', on: :member
    get 'dump', on: :collection
    resources :models
    resources :paths do
      resources :verbs, path: '/requests' do
        resources :query_parameters, only: [] do
          get 'edit', on: :collection
          put 'update', on: :collection
        end
        resources :request_body_properties, only: [] do
          get 'edit', on: :collection
          put 'update', on: :collection
        end
        resources :response_body_properties, only: [] do
          get 'edit', on: :collection
          put 'update', on: :collection
        end
        resources :examples
      end
    end
    resources :path_parameters, only: [] do
      get 'edit', on: :collection
      put 'update', on: :collection
    end
    resources :permissions, only: [] do
      get 'edit', on: :collection
      put 'update', on: :collection
    end
  end

  resources :models, only: [] do
    get 'search', on: :collection
  end

end

app/models/specification.rb
class Specification < ActiveRecord::Base
  default_scope { order("title ASC") }

  validates :version, presence: true, uniqueness: { scope: :title}
  validates :title, presence: true
  has_many :models, dependent: :destroy
  has_many :paths, dependent: :destroy
  has_many :path_parameters, dependent: :destroy
  has_many :permissions, dependent: :destroy

  def display_name
    "#{title} #{version}"
  end

  include ModelUtil

  def used_permissions
    paths.collect(&:verbs).flatten.collect do |verb|
      verb.permissions.split(",").collect(&:strip).reject(&:blank?)
    end.flatten.uniq
  end
  def defined_permissions
    permissions.collect(&:name).uniq
  end
  def used_undefined_permissions
    used_permissions - defined_permissions
  end
  def defined_unused_permissions
    defined_permissions - used_permissions
  end

  def used_path_parameters
    paths.collect{ |path| path.uri.scan(/\{([a-zA-Z]+?)\}/).flatten }.flatten.uniq
  end
  def defined_path_parameters
    path_parameters.collect(&:name).uniq
  end
  def used_undefined_path_parameters
    used_path_parameters - defined_path_parameters
  end
  def defined_unused_path_parameters
    defined_path_parameters - used_path_parameters
  end

  def empty_paths
    paths.select{ |path| path.verbs.blank? }
  end

  def unreferenced_models
    models.select{ |model| model.referenced_by_model.blank? && model.referenced_by_request_body.blank? && model.referenced_by_response_body.blank? }
  end
  def undefined_models
    props = models.collect(&:model_properties).flatten + paths.collect(&:verbs).flatten.collect(&:request_body_properties).flatten
    props += paths.collect(&:verbs).flatten.collect(&:response_body_properties).flatten
    props.collect do |prop| # used model
      if !['integer', 'number', 'string', 'boolean', 'array'].include?(prop.data_type)
        prop.data_type
      elsif prop.data_type == 'array' && !['string'].include?(prop.format)
        prop.format
      else
        nil
      end
    end.reject(&:nil?).reject{ |model| models.find_by_name(model).present? }.uniq
  end

  def no_example_verbs
    paths.collect(&:verbs).flatten.select{ |verb| verb.examples.blank? }
  end

  def update_path_parameters!
    Specification.update_properties!(path_parameters, parse_path_parameters)
  end

  def parse_path_parameters
    Specification.parse(path_parameters_text, PathParameter).collect do |item|
      item.specification = self
      item
    end
  end

  def update_permissions!
    Specification.update_properties!(permissions, parse_permissions)
  end

  def parse_permissions
    lines = permissions_text.strip.split("\n").collect(&:strip).reject(&:blank?)
    perms = lines.collect do |line|
      tokens = line.split("\t").collect(&:strip).reject(&:blank?)
      if tokens.length == 2
        perm = Permission.new
        perm.name = tokens[0]
        perm.description = tokens[1]
        perm.specification = self
        perm
      else
        nil
      end
    end
    perms.reject(&:nil?)
  end

  def swagger(editions = ['Basic'])
    result = {
      swagger: '2.0',
      info: {
        version: version,
        title: title,
        description: description,
        termsOfService: termsOfService,
      },
      host: host,
      basePath: basePath,
      schemes: schemes.split(/\s+/).reject(&:blank?),
      produces: produces.split(/\s+/).reject(&:blank?),
      consumes: consumes.split(/\s+/).reject(&:blank?),
      securityDefinitions: {
        oauth: {
          type: 'oauth2',
          flow: 'accessCode',
          authorizationUrl: 'https://platform.devtest.ringcentral.com/restapi/oauth/authorize',
          tokenUrl: 'https://platform.devtest.ringcentral.com/restapi/oauth/token',
          scopes: {
            default: 'default permissions',
          },
        },
      },
      security: [{
        oauth: ['default'],
      },],
      parameters: Hash[path_parameters.collect{ |pp| [pp.name, { name: pp.name, in: 'path', required: true }.merge(pp.swagger)] }],
      definitions: Hash[models.collect{ |model| [model.name, model.swagger] }],
      paths: {},
    }
    paths.each do |path|
      path_swagger = path.swagger(editions)
      if path_swagger.present?
        result[:paths][path.uri] = path_swagger
      end
    end
    result = JSON[result.to_json] # stringify_keys recursively: https://gist.github.com/mkuhnt/6815250
    result
  end
end

app/controllers/specifications_controller.rb
class SpecificationsController < ApplicationController
  def index
  end

  def new
  end

  def dump
    sql = %x{sqlite3 #{Rails.root.join('db', 'development.sqlite3')} .dump}
    send_data sql, :filename => 'swagger_modeller.sql'
  end

  def create
    spec = Specification.new(spec_params)
    spec.save!
    redirect_to spec
  end

  def show
    @spec = Specification.find(params[:id])
  end

  def edit
    @spec = Specification.find(params[:id])
  end

  def destroy
    Specification.find(params[:id]).destroy
    redirect_to specifications_url
  end

  def update
    spec = Specification.find(params[:id])
    spec.update_attributes(spec_params)
    redirect_to spec
  end

  def swagger
    spec = Specification.find(params[:id])
    editions = (params[:v] || 'Basic').split(',').collect(&:strip)
    respond_to do |format|
      data = spec.swagger(editions)
      format.yaml { render text: data.to_yaml + "\n", content_type: 'text/yaml' }
      format.json { render text: JSON.pretty_generate(data) + "\n", content_type: 'text/json' }
    end
  end

  def validate
    @spec = Specification.find(params[:id])
  end

  def api_reference
    @spec = Specification.find(params[:id])
    respond_to do |format|
      format.md do
        render 'markdown/specification'
      end
      format.html do
        render 'markdown/specification', layout: 'markdown'
      end
    end
  end

  def api_explorer
    spec = Specification.find(params[:id])
    editions = (params[:v] || 'Basic').split(',').collect(&:strip)
    respond_to do |format|
      data = spec.swagger(editions)
      data['paths'].delete('/restapi/oauth/authorize')
      data['paths'].delete('/restapi/oauth/revoke')
      data['paths'].delete('/restapi/oauth/token')
      faxPost = data["paths"]["/restapi/v1.0/account/{accountId}/extension/{extensionId}/fax"]["post"]
      faxPost['consumes'] = ['multipart/mixed; boundary=Boundary_1_14413901_1361871080888']
      faxPost['parameters'] = [{ 'name' => 'body', 'in' => 'body', 'type' => 'string',
        'description' => 'Multi-part MIME consisting of one part JSON body and one part text. For the MIME boundary, in this UI, use "Boundary_1_14413901_1361871080888".',
        'default' => %{--Boundary_1_14413901_1361871080888
Content-Type: application/json

{
  "to":[{"phoneNumber":"18005630003"}],
  "faxResolution":"High"
}

--Boundary_1_14413901_1361871080888
Content-Type: text/plain

Hello World!

--Boundary_1_14413901_1361871080888--} }]
      format.yaml { render text: data.to_yaml + "\n", content_type: 'text/yaml' }
      format.json { render text: JSON.pretty_generate(data) + "\n", content_type: 'text/json' }
    end
  end

  private

  def spec_params
    params.permit(:version, :title, :description,
      :termsOfService, :host, :basePath, :schemes, :consumes, :produces)
  end
end

app/helpers/specifications_helper.rb
module SpecificationsHelper
end

app/views/specifications/_form.html.erb
<br/><%= label_tag(:version, "Version:") %>
<br/><%= text_field_tag(:version, spec.version.presence || "v1.0", class: "form-control") %>
<br/><%= label_tag(:title, "Title:") %>
<br/><%= text_field_tag(:title, spec.title.presence || "RingCentral API", class: "form-control") %>
<br/><%= label_tag(:description, "Description:") %>
<br/><%= text_area_tag(:description, spec.description.presence || "RingCentral Connect Platform API", class: 'article-editor', placeholder: 'Styling with Markdown is supported') %>
<br/><%= label_tag(:termsOfService, "Terms of Service:") %>
<br/><%= text_field_tag(:termsOfService, spec.termsOfService.presence || "http://www.ringcentral.com/legal/eulatos.html", class: "form-control") %>
<br/><%= label_tag(:host, "Host:") %>
<br/><%= text_field_tag(:host, spec.host.presence || "platform.devtest.ringcentral.com", class: "form-control") %>
<br/><%= label_tag(:basePath, "Base Path:") %>
<br/><%= text_field_tag(:basePath, spec.basePath.presence || "/", class: "form-control") %>
<br/><%= label_tag(:schemes, "Schemes:") %>
<br/><%= text_field_tag(:schemes, spec.schemes.presence || "https", class: "form-control") %>
<br/><%= label_tag(:produces, "Produces:") %>
<br/><%= text_field_tag(:produces, spec.produces.presence || "application/json", class: "form-control") %>
<br/><%= label_tag(:consumes, "Consumes:") %>
<br/><%= text_field_tag(:consumes, spec.consumes.presence || "application/json", class: "form-control") %>

app/views/specifications/_info.html.erb
<dl>
  <dt>Version</dt>
  <dd><%= spec.version %></dd>
  <dt>Title</dt>
  <dd><%= spec.title %></dd>
  <dt>Description</dt>
  <dd><%= spec.description %></dd>
  <dt>Terms of Service</dt>
  <dd><%= spec.termsOfService %></dd>
  <dt>Host</dt>
  <dd><%= spec.host %></dd>
  <dt>Base Path</dt>
  <dd><%= spec.basePath %></dd>
  <dt>Schemes</dt>
  <dd><%= spec.schemes %></dd>
  <dt>Produces</dt>
  <dd><%= spec.produces %></dd>
  <dt>Consumes</dt>
  <dd><%= spec.consumes %></dd>
</dl>

app/views/specifications/edit.html.erb
<div class="container">

<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li class="active"><%= @spec.display_name %></li>
</ol>

<h1>Edit a specification</h1>

<%= form_tag(specification_path(@spec), method: "put") do %>
  <%= render partial: 'specifications/form', locals: { spec: @spec } %>
  <br/><%= submit_tag("Update", class: "btn btn-primary") %>
  <%= link_to "Cancel", @spec, class: "btn btn-default" %>
<% end %>

</div>

app/views/specifications/index.html.erb
<div class="container">

<ol class="breadcrumb">
  <li class="active">Home</li>
</ol>

<h1>Specifications</h1>

<table class="table">
  <thead>
    <tr>
      <th>Specification</th>
      <th>Description</th>
      <th>Validate</th>
      <th>Swagger Spec</th>
      <th>API Explorer Spec</th>
      <th>API Reference</th>
    </tr>
  </thead>
  <tbody>
  <% Specification.all.each do |spec| %>
    <tr>
      <td><%= link_to spec.display_name, spec %></td>
      <td><%= truncate spec.description, length: 64 %></td>
      <td><%= link_to 'Validate', validate_specification_path(spec), class: 'btn btn-primary' %></td>
      <td>
        <%= link_to 'JSON', swagger_specification_path(spec, format: 'json', v: 'Basic,Advanced'), class: 'btn btn-info' %>
        <%= link_to 'YAML', swagger_specification_path(spec, format: 'yaml', v: 'Basic,Advanced'), class: 'btn btn-info' %>
      </td>
      <td>
        <%= link_to 'JSON', api_explorer_specification_path(spec, format: 'json', v: 'Basic,Advanced'), class: 'btn btn-info' %>
        <%= link_to 'YAML', api_explorer_specification_path(spec, format: 'yaml', v: 'Basic,Advanced'), class: 'btn btn-info' %>
      </td>
      <td>
        <%= link_to 'Markdown', api_reference_specification_path(spec, format: 'md', v: 'Basic,Advanced'), class: 'btn btn-info' %>
        <%= link_to 'HTML', api_reference_specification_path(spec, format: 'html', v: 'Basic,Advanced'), class: 'btn btn-info' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<hr/>

<% if Specification.count == 0 %>
<a href="/specifications/new" class="btn btn-primary">Create a specification</a>
<% end %>

<!--
<%= link_to "Dump DB", dump_specifications_path, class: "btn btn-success" %>

<h2>Load DB</h2>

<p>In order to load `swagger_modeller.sql` into db, you need to do the following:</p>
<ol>
  <li>Stop `rails s`</li>
  <li>Back up database `db/development.sqlite3`</li>
  <li>`rm db/development.sqlite3`</li>
  <li>`sqlite3 db/development.sqlite3 < swagger_modeller.sql`</li>
</ol>
-->

</div>

app/views/specifications/new.html.erb
<div class="container">

<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li class="active">Create a specification</li>
</ol>

<h1>Create a specification</h1>

<%= form_tag(specifications_path, method: "post") do %>
  <%= render partial: 'specifications/form', locals: { spec: Specification.new } %>
  <br/><%= submit_tag("Create", class: "btn btn-primary") %>
  <a href="/" class="btn btn-default">Cancel</a>
<% end %>

</div>

app/views/specifications/show.html.erb
<div class="container">

<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li class="active"><%= @spec.display_name %></li>
</ol>

<h1><%= @spec.display_name %></h1>
<%= link_to 'Back', root_path, class: "btn btn-info" %>
<%= link_to 'Edit', edit_specification_path(@spec), class: "btn btn-primary" %>
<%= link_to 'Destroy', @spec, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", :method => :delete %>

<hr/>

<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active"><a href="#info" aria-controls="info" role="tab" data-toggle="tab">Info</a></li>
  <li role="presentation"><a href="#permissions" aria-controls="permissions" role="tab" data-toggle="tab">Permissions</a></li>
  <li role="presentation"><a href="#path_parameters" aria-controls="path_parameters" role="tab" data-toggle="tab">Path Parameters</a></li>
  <li role="presentation"><a href="#paths" aria-controls="paths" role="tab" data-toggle="tab">Paths</a></li>
  <li role="presentation"><a href="#models" aria-controls="models" role="tab" data-toggle="tab">Models</a></li>
</ul>

<div class="tab-content">

<!-- tab #1: info -->
<div role="tabpanel" class="tab-pane active" id="info">
  <%= render partial: 'specifications/info', locals: { spec: @spec } %>
</div><!-- tab #1 -->

<!-- tab #2: permissions -->
<div role="tabpanel" class="tab-pane" id="permissions">
  <p><br/><%= link_to "Edit", edit_specification_permissions_path(@spec), class: "btn btn-primary" %></p>
  <%= render partial: 'shared/permissions', locals: { permissions: @spec.permissions } %>
</div><!-- tab #2 -->

<!-- tab #3: path_parameters -->
<div role="tabpanel" class="tab-pane" id="path_parameters">
  <p><br/><%= link_to "Edit", edit_specification_path_parameters_path(@spec), class: "btn btn-primary" %></p>
  <%= render partial: 'shared/properties', locals: { properties: @spec.path_parameters } %>
</div><!-- tab #3 -->

<!-- tab #4: paths -->
<div role="tabpanel" class="tab-pane" id="paths">
  <p>
  <br/><%= link_to "Create a path", new_specification_path_path(@spec), class: "btn btn-primary" %>
  </p>
  <table class="table">
    <% @spec.paths.each_with_index do |path, index| %>
      <tr><td>
        <%= index + 1 %>.
        &nbsp; <%= link_to path.uri, specification_path_path(@spec, path) %>
        &nbsp; <%= path_status(path) %>
      </td></tr>
    <% end %>
  </table>
</div><!-- tab #4 -->

<!-- tab #5: models -->
<div role="tabpanel" class="tab-pane" id="models">
  <p>
  <br/><%= link_to "Create a model", new_specification_model_path(@spec), class: "btn btn-primary" %>
  </p>
  <table class="table">
    <% @spec.models.each_with_index do |model, index| %>
      <tr><td>
        <%= index + 1 %>.
        &nbsp; <%= link_to model.name, specification_model_path(@spec, model) %>
        &nbsp; <span class="badge" data-toggle="tooltip" data-placement="right" title="<%= pluralize model.model_properties.count, "property" %>"><%= model.model_properties.count %></span>
      </td></tr>
    <% end %>
  </table>
</div><!-- tab #5 -->

</div><!-- tabs -->

</div><!-- container -->

app/views/specifications/validate.html.erb
<div class="container">

<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><%= link_to @spec.display_name, specification_path(@spec) %></li>
  <li class="active">Validation</li>
</ol>

<h1><%= @spec.display_name %> validation</h1>

<h2>Permissions</h2>

<% if @spec.used_undefined_permissions.present? %>
  <div class="alert alert-danger" role="alert">The following permissions are used but undefined: <%= @spec.used_undefined_permissions.join(', ') %></div>
<% elsif @spec.defined_unused_permissions.present? %>
  <div class="alert alert-warning" role="alert">The following permissions are defined but unused: <%= @spec.defined_unused_permissions.join(', ') %></div>
<% else %>
  <div class="alert alert-success" role="alert">Everything seems fine!</div>
<% end %>

<h2>Tags</h2>

<% has_error = false %>
<% @spec.paths.each do |path| %>
  <% path.verbs.each do |verb| %>
    <% if verb.tags.length == 0 %>
      <% has_error = true %>
      <div class="alert alert-danger" role="alert"><%= verb.method %> <%= path.uri %> has no tags.</div>
    <% end %>
  <% end %>
<% end %>
<% if has_error == false %>
  <div class="alert alert-success" role="alert">Everything seems fine!</div>
<% end %>

<h2>Path parameters</h2>

<% if @spec.used_undefined_path_parameters.present? %>
  <div class="alert alert-danger" role="alert">The following path parameters are used but undefined: <%= @spec.used_undefined_path_parameters.join(', ') %></div>
<% elsif @spec.defined_unused_path_parameters.present? %>
  <div class="alert alert-warning" role="alert">The following path parameters are defined but unused: <%= @spec.defined_unused_path_parameters.join(', ') %></div>
<% else %>
  <div class="alert alert-success" role="alert">Everything seems fine!</div>
<% end %>

<h2>Paths</h2>

<% if @spec.empty_paths.present? %>
  <div class="alert alert-warning" role="alert">The following paths are empty: <%= @spec.empty_paths.collect(&:uri).join(', ') %></div>
<% else %>
  <div class="alert alert-success" role="alert">Everything seems fine!</div>
<% end %>

<h2>Models</h2>

<% if @spec.undefined_models.present? %>
  <div class="alert alert-danger" role="alert">The following models are used but undefined: <%= @spec.undefined_models.join(', ') %></div>
<% elsif @spec.unreferenced_models.present? %>
  <div class="alert alert-warning" role="alert">The following models are defined but unused: <%= @spec.unreferenced_models.collect(&:name).join(', ') %></div>
<% else %>
  <div class="alert alert-success" role="alert">Everything seems fine!</div>
<% end %>

<h2>Examples</h2>

<% if @spec.no_example_verbs.present? %>
  <div class="alert alert-warning" role="alert">The following requests have no examples: <%= @spec.no_example_verbs.collect(&:name).join(', ') %></div>
<% else %>
  <div class="alert alert-success" role="alert">Everything seems fine!</div>
<% end %>

</div>