config/routes.rb
Rails.application.routes.draw do

  root 'specifications#index'

  resources :specifications do
    get 'validate', on: :member
    get 'swagger', on: :member
    get 'api_explorer', on: :member
    get 'api_reference', on: :member
    get 'dump', on: :collection
    resources :models
    resources :paths do
      resources :verbs, path: '/requests' do
        resources :query_parameters, only: [] do
          get 'edit', on: :collection
          put 'update', on: :collection
        end
        resources :request_body_properties, only: [] do
          get 'edit', on: :collection
          put 'update', on: :collection
        end
        resources :response_body_properties, only: [] do
          get 'edit', on: :collection
          put 'update', on: :collection
        end
        resources :examples
      end
    end
    resources :path_parameters, only: [] do
      get 'edit', on: :collection
      put 'update', on: :collection
    end
    resources :permissions, only: [] do
      get 'edit', on: :collection
      put 'update', on: :collection
    end
  end

  resources :models, only: [] do
    get 'search', on: :collection
  end

end

app/models/response_body_property.rb
class ResponseBodyProperty < ActiveRecord::Base
  default_scope { order("position ASC") }

  validates :verb_id, presence: true
  validates :name, presence: true, uniqueness: { scope: :verb_id }
  validates :description, presence: true
  belongs_to :verb

  include PropertyUtil
end

app/controllers/response_body_properties_controller.rb
class ResponseBodyPropertiesController < ApplicationController
  def edit
    @spec = Specification.find(params[:specification_id])
    @path = Path.find(params[:path_id])
    @verb = Verb.find(params[:verb_id])
  end

  def update
    @spec = Specification.find(params[:specification_id])
    @path = Path.find(params[:path_id])
    @verb = Verb.find(params[:verb_id])
    @verb.response_body_text = params[:response_body_text]
    @verb.save!
    redirect_to specification_path_verb_path(@spec, @path, @verb, anchor: 'response_body')
  end
end

app/helpers/response_body_properties_helper.rb
module ResponseBodyPropertiesHelper
end

app/views/response_body_properties/edit.html.erb
<div class="container">

<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><%= link_to @spec.display_name, specification_path(@spec, anchor: 'paths') %></li>
  <li><%= link_to @path.uri, specification_path_path(@spec, @path) %></li>
  <li><%= link_to "[#{@verb.method}] " + @verb.name, specification_path_verb_path(@spec, @path, @verb) %></li>
  <li class="active">Response Body</li>
</ol>

<h1>Edit Response Body</h1>

<%= form_tag(specification_path_verb_response_body_properties_path(@spec, @path, @verb), method: "put") do %>
  <%= text_area_tag(:response_body_text, @verb.response_body_text, class: "properties-editor") %>
  <br/><%= submit_tag("Update", class: "btn btn-primary") %>
  <%= link_to "Cancel", specification_path_verb_path(@spec, @path, @verb, anchor: 'response_body'), class: "btn btn-default" %>
<% end %>

</div>