config/routes.rb
Rails.application.routes.draw do

  root 'specifications#index'

  resources :specifications do
    get 'validate', on: :member
    get 'swagger', on: :member
    get 'api_explorer', on: :member
    get 'api_reference', on: :member
    get 'dump', on: :collection
    resources :models
    resources :paths do
      resources :verbs, path: '/requests' do
        resources :query_parameters, only: [] do
          get 'edit', on: :collection
          put 'update', on: :collection
        end
        resources :request_body_properties, only: [] do
          get 'edit', on: :collection
          put 'update', on: :collection
        end
        resources :response_body_properties, only: [] do
          get 'edit', on: :collection
          put 'update', on: :collection
        end
        resources :examples
      end
    end
    resources :path_parameters, only: [] do
      get 'edit', on: :collection
      put 'update', on: :collection
    end
    resources :permissions, only: [] do
      get 'edit', on: :collection
      put 'update', on: :collection
    end
  end

  resources :models, only: [] do
    get 'search', on: :collection
  end

end

app/models/verb.rb
# Verb is a synonym for Request

class Verb < ActiveRecord::Base
  validates :path_id, presence: true
  validates :method, presence: true
  validates :visibility, presence: true
  validates :name, presence: true, uniqueness: { scope: :path_id }
  belongs_to :path
  has_many :query_parameters, dependent: :destroy
  has_many :request_body_properties, dependent: :destroy
  has_many :response_body_properties, dependent: :destroy
  has_many :examples, dependent: :destroy

  include ModelUtil

  def query_parameters_text=(value)
    write_attribute(:query_parameters_text, value)
    Verb.update_properties!(query_parameters, parse_parameters)
  end

  def parse_parameters
    Verb.parse(query_parameters_text, QueryParameter).collect do |item|
      item.verb = self
      item
    end
  end

  def request_body_text=(value)
    write_attribute(:request_body_text, value)
    Verb.update_properties!(request_body_properties, parse_request_properties)
  end

  def response_body_text=(value)
    write_attribute(:response_body_text, value)
    Verb.update_properties!(response_body_properties, parse_response_properties)
  end

  def parse_request_properties
    Verb.parse(request_body_text, RequestBodyProperty).collect do |item|
      item.verb = self
      item
    end
  end

  def parse_response_properties
    Verb.parse(response_body_text, ResponseBodyProperty).collect do |item|
      item.verb = self
      item
    end
  end

  def swagger(editions = ['Basic'])
    if not (editions.detect{ |edition| visibility.include?(edition) }.present? && (status == '' || status == 'Normal'))
      return nil
    end

    result = {
      tags: tags.split(',').collect{ |tag| tag.strip },
      description: name,
      responses: {
        default: {
          description: 'OK',
        },
      },
    }

    ### parameters ###

    # query parameters
    parameters = query_parameters.collect do |qp|
      item = qp.swagger
      item[:name] = qp.name
      item[:in] = 'query'
      item
    end

    # request body parameters
    request_body = { name: 'body', in: 'body', schema: {} }
    if request_body_properties.present? # table of properties
      request_body[:schema] = { type: 'object', properties: {} }
      request_body_properties.each do |rbp|
        request_body[:schema][:properties][rbp.name] = rbp.swagger
      end
    else
      if request_body_text.present?
        if request_body_text.include? "\n" # enum of models
          request_body[:schema] = {
            type: 'object',
            enum: request_body_text.split(/[\r\n]+/).reject(&:blank?).collect do |model|
              { '$ref' => "#/definitions/#{model}" }
            end
          }
        else # model
          request_body[:schema] = { '$ref' => "#/definitions/#{request_body_text}" }
        end
      end
    end
    if request_body[:schema].present?
      parameters << request_body
    end

    if parameters.present?
      result[:parameters] = parameters
    end

    ### response ###
    if response_body_properties.blank?
      if response_body_text.present? # model name
        result[:responses][:default][:schema] = { '$ref' => "#/definitions/#{response_body_text}" }
      else
        # no response at all
      end
    else # list of properties
      result[:responses][:default][:schema] = { type: 'object', properties: {} }
      response_body_properties.each do |rbp|
        result[:responses][:default][:schema][:properties][rbp.name] = rbp.swagger
      end
    end

    return result

  end
end

app/controllers/verbs_controller.rb
class VerbsController < ApplicationController
  def show
    @spec = Specification.find(params[:specification_id])
    @path = Path.find(params[:path_id])
    @verb = Verb.find(params[:id])
  end

  def new
    @spec = Specification.find(params[:specification_id])
    @path = Path.find(params[:path_id])
  end

  def create
    spec = Specification.find(params[:specification_id])
    path = Path.find(params[:path_id])
    verb = Verb.new(verb_params)
    verb.save!
    redirect_to specification_path_verb_url(spec, path, verb)
  end

  def destroy
    Verb.find(params[:id]).destroy
    spec = Specification.find(params[:specification_id])
    path = Path.find(params[:path_id])
    redirect_to specification_path_url(spec, path)
  end

  def edit
    @spec = Specification.find(params[:specification_id])
    @path = Path.find(params[:path_id])
    @verb = Verb.find(params[:id])
  end

  def update
    spec = Specification.find(params[:specification_id])
    path = Path.find(params[:path_id])
    verb = Verb.find(params[:id])
    verb.update_attributes(verb_params)
    redirect_to specification_path_verb_url(spec, path, verb)
  end

  private

  def verb_params
    result = params.permit(:name, :since, :description, :visibility, :method, :api_group, :permissions, :tags, :batch, :status, :path_id)
    result[:batch] = result[:batch] == 'Yes'
    return result
  end
end

app/helpers/verbs_helper.rb
module VerbsHelper
  def verb_status(verb)
    if verb.status == '' || verb.status == 'Normal'
      return raw '<span class="label label-success">Normal</span>'
    end
    if verb.status == 'Deprecated'
      return raw '<span class="label label-warning">Deprecated</span>'
    end
    if verb.status == 'Disabled' || verb.status == 'NoDoc'
      return raw "<span class=\"label label-danger\">#{verb.status}</span>"
    end
    return raw "<span class=\"label label-info\">#{verb.status}</span>"
  end

  def verb_visibility(verb)
    if verb.visibility.include? 'Internal'
      return raw "<span class=\"label label-warning\">#{verb.visibility}</span>"
    end
    if verb.visibility.include? 'Advanced'
      return raw "<span class=\"label label-info\">#{verb.visibility}</span>"
    end
    if verb.visibility.include? 'Basic'
      return raw "<span class=\"label label-success\">#{verb.visibility}</span>"
    end
    return raw "<span class=\"label label-info\">#{verb.visibility}</span>"
  end
end

app/views/verbs/_form.html.erb
<br/><%= label_tag(:name, "Name:") %>
<br/><%= text_field_tag(:name, verb.name.presence || '', class: "form-control", placeholder: "What is this request about?") %>
<br/><%= label_tag(:since, "Since:") %>
<br/><%= text_field_tag(:since, verb.since.presence || '', class: "form-control", placeholder: "1.0.24 (Release 8.0)") %>
<br/><%= label_tag(:description, "Description:") %>
<br/><%= text_area_tag(:description, verb.description.presence || '', class: 'article-editor', placeholder: 'Styling with Markdown is supported') %>
<br/><%= label_tag(:method, "Method:") %>
<br/><%= select_tag(:method, options_for_select(['GET', 'POST', 'PUT', 'DELETE'], verb.method.presence || 'GET'), class: "form-control") %>
<br/><%= label_tag(:api_group, "API Group:") %>
<br/><%= select_tag(:api_group, options_for_select(['Light', 'Medium', 'Heavy', 'Auth'], verb.api_group.presence || 'Light'), class: "form-control") %>
<br/><%= label_tag(:permissions, "Required Permissions:") %>
<br/><%= text_field_tag(:permissions, verb.permissions.presence || '', class: "form-control", placeholder: "Multiple permissions separated by commas") %>
<br/><%= label_tag(:tags, "Tags:") %>
<br/><%= text_field_tag(:tags, verb.tags.presence || '', class: "form-control", placeholder: "Multiple tags separated by commas") %>
<br/><%= label_tag(:batch, "Batch:") %>
<br/><%= select_tag(:batch, options_for_select(['Yes', 'No'], verb.batch ? 'Yes' : 'No'), class: "form-control") %>
<br/><%= label_tag(:visibility, "Visibility:") %>
<br/><%= select_tag(:visibility, options_for_select(['Public Basic', 'Public Advanced', 'Public Internal', 'Internal', 'Integration'], verb.visibility.presence || 'Public Basic'), class: "form-control") %>
<br/><%= label_tag(:status, "Status:") %>
<br/><%= select_tag(:status, options_for_select(['Normal', 'Deprecated', 'Disabled', 'NoDoc'], verb.status.presence || 'Normal'), class: "form-control") %>

app/views/verbs/_info.html.erb
<dl>
  <dt>Since</dt>
  <dd><%= verb.since %></dd>
  <dt>Description</dt>
  <dd><pre><%= verb.description %></pre></dd>
  <dt>Method</dt>
  <dd><%= verb.method %></dd>
  <dt>API Group</dt>
  <dd><%= verb.api_group %></dd>
  <dt>Required Permissions</dt>
  <dd><%= verb.permissions %></dd>
  <dt>Tags</dt>
  <dd><%= verb.tags %></dd>
  <dt>Batch</dt>
  <dd><%= verb.batch %></dd>
  <dt>Visibility</dt>
  <dd><%= verb_visibility(verb) %></dd>
  <dt>status</dt>
  <dd><%= verb_status(verb) %></dd>
</dl>

app/views/verbs/edit.html.erb
<div class="container">

<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><%= link_to @spec.display_name, specification_path(@spec, anchor: 'paths') %></li>
  <li><%= link_to @path.uri, specification_path_path(@spec, @path) %></li>
  <li class="active">[<%= @verb.method %>] <%= @verb.name %></li>
</ol>

<h1>Edit a request</h1>

<%= form_tag(specification_path_verb_path(@spec, @path, @verb), method: "put") do %>
  <%= render partial: 'verbs/form', locals: { verb: @verb } %>
  <br/><%= submit_tag("Update", class: "btn btn-primary") %>
  <%= link_to "Cancel", specification_path_verb_path(@spec, @path, @verb), class: "btn btn-default" %>
<% end %>

</div>

app/views/verbs/new.html.erb
<div class="container">

<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><%= link_to @spec.display_name, specification_path(@spec, anchor: 'paths') %></li>
  <li><%= link_to @path.uri, specification_path_path(@spec, @path) %></li>
  <li class="active">Create a request</li>
</ol>

<h1>Create a request</h1>

<%= form_tag(specification_path_verbs_path(@spec, @path), method: "post") do %>
  <%= render partial: 'verbs/form', locals: { verb: Verb.new } %>
  <br/><%= submit_tag("Create", class: "btn btn-primary") %>
  <%= link_to "Cancel", specification_path_path(@spec, @path), class: "btn btn-default" %>
<% end %>

</div>

app/views/verbs/show.html.erb
<div class="container">

<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><%= link_to @spec.display_name, specification_path(@spec, anchor: 'paths') %></li>
  <li><%= link_to @path.uri, specification_path_path(@spec, @path) %></li>
  <li class="active">[<%= @verb.method %>] <%= @verb.name %></li>
</ol>

<h1><%= @verb.name %></h1>
<%= link_to 'Back', specification_path_path(@spec, @path), class: "btn btn-info" %>
<%= link_to 'Edit', edit_specification_path_verb_path(@spec, @path, @verb), class: "btn btn-primary" %>
<%= link_to 'Destroy', specification_path_verb_path(@spec, @path, @verb), data: { confirm: 'Are you sure?' }, class: "btn btn-danger", :method => :delete %>

<hr/>

<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active"><a href="#info" aria-controls="info" role="tab" data-toggle="tab">Info</a></li>
  <li role="presentation"><a href="#query_parameters" aria-controls="query_parameters" role="tab" data-toggle="tab">Query Parameters</a></li>
  <li role="presentation"><a href="#request_body" aria-controls="request_body" role="tab" data-toggle="tab">Request Body</a></li>
  <li role="presentation"><a href="#response_body" aria-controls="response_body" role="tab" data-toggle="tab">Response Body</a></li>
  <li role="presentation"><a href="#examples" aria-controls="examples" role="tab" data-toggle="tab">Examples</a></li>
</ul>

<div class="tab-content">

<!-- tab #1: info -->
<div role="tabpanel" class="tab-pane active" id="info">
  <%= render partial: 'verbs/info', locals: { verb: @verb } %>
</div><!-- tab #1 -->

<!-- tab #2: Query Parameters -->
<div role="tabpanel" class="tab-pane" id="query_parameters">
  <p><br/><%= link_to "Edit", edit_specification_path_verb_query_parameters_path(@spec, @path, @verb), class: "btn btn-primary" %></p>
  <% if @verb.query_parameters.count > 0 %>
    <%= render partial: 'shared/properties', locals: { properties: @verb.query_parameters } %>
  <% end %>
</div><!-- tab #2 -->

<!-- tab #3: Request Body -->
<div role="tabpanel" class="tab-pane" id="request_body">
  <p><br/><%= link_to "Edit", edit_specification_path_verb_request_body_properties_path(@spec, @path, @verb), class: "btn btn-primary" %></p>
  <% if @verb.request_body_properties.count == 0 %>
    <p><%= link_to_model @verb.request_body_text %></p>
  <% else %>
    <%= render partial: 'shared/properties', locals: { properties: @verb.request_body_properties } %>
  <% end %>
</div><!-- tab #3 -->

<!-- tab #4: Response Body -->
<div role="tabpanel" class="tab-pane" id="response_body">
  <p><br/><%= link_to "Edit", edit_specification_path_verb_response_body_properties_path(@spec, @path, @verb), class: "btn btn-primary" %></p>
  <% if @verb.response_body_properties.count == 0 %>
    <p><%= link_to_model @verb.response_body_text %></p>
  <% else %>
    <%= render partial: 'shared/properties', locals: { properties: @verb.response_body_properties } %>
  <% end %>
</div><!-- tab #4 -->

<!-- tab #5: Examples -->
<div role="tabpanel" class="tab-pane" id="examples">
  <p>
    <br/><%= link_to "Create an example", new_specification_path_verb_example_path(@spec, @path, @verb), class: "btn btn-primary" %>
  </p>
  <% @verb.examples.each do |example| %>
    <h3>
      <%= example.name %>
      <%= link_to 'Edit', edit_specification_path_verb_example_path(@spec, @path, @verb, example), class: "btn btn-primary btn-xs" %>
      <%= link_to 'Destroy', specification_path_verb_example_path(@spec, @path, @verb, example), data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs", :method => :delete %>
    </h3>
    <p><%= example.description %></p>
    <h4>Request</h4>
    <pre><%= example.request %></pre>
    <h4>Response</h4>
    <pre><%= example.response %></pre>
    <hr/>
  <% end %>
</div><!-- tab #5 -->

</div><!-- tabs -->
</div>